version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:22.6.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-hash-{{ checksum "yarn.lock" }}
            - deps-hash-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: deps-hash-{{ checksum "yarn.lock" }}
      - run: 
          name: "Run unit tests with coverage"
          command: yarn unit-test
      - run:
          name: "Download and run Codecov uploader"
          command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov -f ./coverage/lcov.info
      - store_artifacts:
          path: coverage
          destination: coverage
      - run: yarn build
